name: Test

on:
  schedule:
    - cron: "0 6 * * 1-5"
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'main'
      
# Auto cancel previous runs if they were not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-edamame-posture:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    steps:
      # We don't use the EDAMAME Posture Action here, because we want to fully test the action.yml file
      - name: Checkout
        uses: actions/checkout@v4

      # Test start
      - name: Test start
        id: test-start
        uses: ./ # Use the local action definition (action.yaml)
        with:
          edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
          edamame_id: ${{ github.run_id }}
          # Don't checkout the repo, we already did that in the previous step
          checkout: false
          report_email: dev@edamame.tech
        continue-on-error: true
        
      # Test check-policy (local)
      - name: Test check-policy (local)
        id: test-check-policy-local
        uses: ./
        with:
          edamame_minimum_score: 1.0
          edamame_mandatory_threats: "encrypted disk disabled"
          edamame_mandatory_prefixes: ""
        continue-on-error: true
        
      # Test check-policy-for-domain
      - name: Test check-policy-for-domain
        id: test-check-policy-for-domain
        uses: ./
        with:
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_policy: "Github"
        continue-on-error: true

      # Test check-policy (local)
      - name: Test check-policy (local)
        id: test-check-policy-local-error
        uses: ./
        with:
          edamame_minimum_score: 5.0
          edamame_mandatory_threats: "no EPP"
          edamame_mandatory_prefixes: ""
        continue-on-error: true
      
      # Test check-policy-for-domain
      - name: Test check-policy-for-domain
        id: test-check-policy-for-domain-error
        uses: ./
        with:
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_policy: "Invalid policy"
        continue-on-error: true

      - name: Slack alerts
        if: steps.test-start.outcome != 'success' || steps.test-check-policy-local.outcome != 'success' || steps.test-check-policy-for-domain.outcome != 'success' || steps.test-check-policy-local-error.outcome == 'success' || steps.test-check-policy-for-domain-error.outcome == 'success'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072J0U9TH7'
          slack-message: "Tests ran in ${{ github.workflow }} for ${{ github.repository }} for ${{ runner.os }} on branch ${{ github.ref }} failed: see https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Fail job if tests failed
        if: steps.test-start.outcome != 'success' || steps.test-check-policy-local.outcome != 'success' || steps.test-check-policy-for-domain.outcome != 'success' || steps.test-check-policy-local-error.outcome == 'success' || steps.test-check-policy-for-domain-error.outcome == 'success'
        run: |
          echo "Forcing job to fail because tests did not succeed."
          exit 1